id: P009181
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD17439
  title: དམངས་དོན་གཏུག་བཤེར་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    251b4597aea74672956a05950c600360:
      image_group_id: I2PD17965
      title: ''
      volume_number: 1
      total_pages: 460
      base_file: v001.txt
