id: P009181
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17439
  title: དམངས་དོན་གཏུག་བཤེར་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    251b4597aea74672956a05950c600360:
      image_group_id: I2PD17965
      title: ''
      volume_number: 1
      total_pages: 460
