id: I5472C894
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:31:31+00:00'
last_modified: '2022-06-08T09:11:43.554978+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17439
  title: དམངས་དོན་གཏུག་བཤེར་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    BAC9:
      image_group_id: I2PD17965
      title: ''
      total_pages: 460
      order: 1
      base_file: BAC9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
